version: 2.1
workflows:
  testing:
    jobs:
      - runner
jobs:
  runner:
    machine: true
    resource_class: zenika/lyon-mobileapps
    steps:
      - checkout
      - run: bundle install
      - run:
          name: list of certificates
          command: security find-identity -v -p codesigning fastlane_tmp_keychain
      - run:
          name: Fastlane
          command: bundle exec fastlane build
      - store_artifacts:
          path: output/Game.ipa