#Choose your import : Local or Remote

#Local Fastfile
#import "../../../Fastlane-Template/fastlane/Fastfile-iOS"

#Remote Fastfile
import_from_git(
  url: "git@github.com:Zenika/Fastlane-Template.git", # The URL of the repository to import the Fastfile from.
  branch: "main", # The branch to checkout on the repository.
  path: "fastlane/Fastfile-iOS", # The path of the Fastfile in the repository.
  version: "0.0.5" # The version to checkout on the repository. Optimistic match operator can be used to select the latest version within constraints.
)

platform :ios do
  before_all do |lane|
    setup_project
  end

  desc "Init project variables"
  lane :setup_project do
    init_project(
      xcodeproj: ENV["XCODEPROJ"],
      target: ENV["TARGET"],
      scheme: ENV["SCHEME"],
      configuration: ENV["CONFIGURATION"],
      output_directory: ENV["OUTPUT_DIRECTORY"],
      output_name: ENV["OUTPUT_NAME"],
      match_type: ENV["MATCH_TYPE"]
    ) 
  end

  desc "Build"
  lane :build_ios do
    bump_version_number_and_build_number(version: ENV["REGEX"], build_number:ENV["BUILD_NUMBER"])
    display_badge_on_appIcon(badge: "alpha", dark:true, version:true) #badge: alpha or beta or no-badge, dark: true or false(light) 
    download_certificates_and_profiles
    build
  end

  desc "Deploy"
  lane :deploy_ios do |options|
    generate_release_note(env: ENV["RELEASE_NOTE_ENV"])

    #Choose the deploy lane: deploy_firebase_app_tester or deploy_appstore
    deploy_firebase_app_tester(
      token: ENV["FIREBASE_TOKEN"],
      googleservice_info_plist_path: "./GoogleService-Info.plist"
    )
    
    # deploy_appstore(
    #   team_id: ENV["TEAM_ID"],
    #   team_name: ENV["TEAM_NAME"]
    # )

  end
end
